#-------------------------------------------------------------------------------
# 
# Copyright (C) 2006 HLVM Group. All Rights Reserved
#
#-------------------------------------------------------------------------------

LEVEL 			:= ../../..
LIBRARYNAME 		:= HLVMXMLWriter
DONT_BUILD_RELINKED 	:= 1
BUILD_ARCHIVE 		:= 1
INSTALL_INCLUDES 	:= XMLWriter.h

include $(LEVEL)/Makefile.hlvm
