#-------------------------------------------------------------------------------
# 
# Copyright (C) 2006 HLVM Group. All Rights Reserved
#
#-------------------------------------------------------------------------------

LEVEL 	            := ../..
LIBRARYNAME         := HLVMPass
DONT_BUILD_RELINKED := 1
BUILD_ARCHIVE       := 1
INSTALL_INCLUDES    := Validate.h

include $(LEVEL)/Makefile.hlvm
