##===- hlvm/Reader/XML/Makefile ----------------------------*- Makefile -*-===##
LEVEL=../../..
DIRS=
LIBRARYNAME = HLVMYamlReader
DONT_BUILD_RELINKED := 1
BUILD_ARCHIVE := 1
INSTALL_INCLUDES := YamlReader.h

include $(LEVEL)/Makefile.hlvm
