#===- autoconf/Makefile ------------------------------------*- Makefile -*--===#
# 
#                     The LLVM Support Autoconf Makefile
#
# This file was developed by the Reid Spencer and is distributed under the
# University of Illinois Open Source License. See LICENSE.TXT for details.
# 
#===------------------------------------------------------------------------===#
-include ./Makefile.mod
