##===- hlvm/Base/Makefile ----------------------------------*- Makefile -*-===##
#
LEVEL=../..
DIRS=
LIBRARYNAME = HLVMBase
DONT_BUILD_RELINKED := 1
BUILD_ARCHIVE := 1
INSTALL_INCLUDES := Config.h URI.h URI.i


include $(LEVEL)/Makefile.hlvm
