#!/bin/sh
#                               get script
# 
# This file was developed by Reid Spencer and is distributed under the
# University of Illinois Open Source License. See LICENSE.TXT for details.
# 
#===------------------------------------------------------------------------===#

# This script allows easier checkout of LLVM modules. Just specify the names
# of the modules on the command line. See the README.txt file.

# Get the shell function library.
if test ! -z "$LLVM_TOP" ; then
  if test -f "$LLVM_TOP/library.sh" ; then
    . "$LLVM_TOP/library.sh"
  else
    echo "Your LLVM_TOP variable is not set to an llvm-top directory"
    exit 1
  fi
elif test -f ./library.sh ; then
  . ./library.sh
elif test -f ../library.sh ; then
  . ../library.sh
else
  echo Please run $0 from the llvm-top directory or a module directory.
  exit 1
fi

# Get the list of modules
process_arguments "$@"

# Getting the module dependencies also causes them to be checked out.
get_module_dependencies $MODULES

# Report what happened.
msg 1 Modules checked out:"$MODULE_DEPENDENCIES".
