#!/bin/sh
#                                   info script
# 
# This file was developed by Reid Spencer and is distributed under the
# University of Illinois Open Source License. See LICENSE.TXT for details.
# 
#===------------------------------------------------------------------------===#

# This script gets subversion information about each module checked out. Just
# specify the list of modules your' interested in or specify none to get show
# information about the currently checked out modules. See the README.txt file.

# Get the library.
. ./library.sh

# Get the list of modules
process_arguments "$@"

# Getting the module dependencies also causes them to be checked out.
get_module_dependencies $MODULES

for mod in $MODULE_DEPENDENCIES ; do
  msg 0 "Information for module '$mod'"
  svn info $mod | sed -e '/^Repository/d' -e '/^Node/d' -e '/^Sched/d'
done
