Import('env')
from scons import main
main.GetRNGQuoteSource(env)
main.GetRNGTokenizer(env)
env.RNGQuoteSource('HLVM.rng.inc','HLVM.rng')
env.RNGTokenizer('HLVMTokenizer.cpp','HLVM.rng')
env.Library('HLVMXMLReader',main.GetAllCXXFiles(env))
