#-------------------------------------------------------------------------------
# 
# Copyright (C) 2006 HLVM Group. All Rights Reserved
#
#-------------------------------------------------------------------------------

LEVEL 	            := ../..
LIBRARYNAME         := HLVMAST
DONT_BUILD_RELINKED := 1
BUILD_ARCHIVE       := 1
INSTALL_INCLUDES    := Bundle.h Conditionable.h ContainerType.h Function.h \
                       LinkageItem.h Node.h SymbolTable.h Type.h Variable.h

include $(LEVEL)/Makefile.hlvm
