##==-- test/Makefile.test - Common make rules Java tests -*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

.PHONY: clean

clean::
	$(Verb)$(RM) -f a.out core
	$(Verb)$(RM) -rf Output/

# we don't want these files to be deleted by make, even if they are
# intermediate results
.PRECIOUS: %.linked.bc %.raw.bc %.ll %.llvm.bc

# rule to link bytecode with runtime
%.llvm %.llvm.bc: %.linked.bc $(LibDir)/libjrt.bca $(EXTRA_OBJS) $(LOPT)
	$(Echo) Linking $< with the Java runtime
	-$(Verb)$(GCCLD) -o=$*.llvm $< -L $(CFERuntimeLibDir) -L $(LibDir) $(EXTRA_OBJS)

# rule to link raw bytecode with runtime
%.raw.llvm %.raw.llvm.bc: %.raw.bc $(LibDir)/libjrt.bca $(EXTRA_OBJS) $(LOPT)
	$(Echo) Linking $< with the Java runtime
	-$(Verb)$(GCCLD) -disable-opt -o=$*.raw.llvm $< -L $(CFERuntimeLibDir) -L $(LibDir) $(EXTRA_OBJS)

# add function trace code
%.tracef.llvm %.tracef.llvm.bc: %.llvm %.llvm.bc $(LOPT)
	$(Echo) Adding function trace code to $<
	$(Verb)$(CP) $*.llvm $*.tracef.llvm
	$(Verb)$(LOPT) -tracem -tracedisablehashdisable -f -o=$*.tracef.llvm.bc $*.llvm.bc

# rule to make assembly from bytecode
%.dis-ll: %.bc
	$(Echo) Disassembling $<
	$(Verb)$(LDIS) -f -o=$@ $<

# rule to compile java sources
ifdef BUILD_JAVA_SOURCES
JAVA_SOURCES := $(wildcard *.java)
JAVA_TESTS := $(basename $(JAVA_SOURCES))
PREFIXED_JAVA_TESTS := $(addprefix Output/, $(JAVA_TESTS))
PREFIXED_CLASS_FILES := $(addsuffix .class/, $(PREFIXED_JAVA_TESTS))

$(PREFIXED_CLASS_FILES): $(addsuffix .java,$(JAVA_TESTS))
	$(Echo) Compiling $?
	$(Verb)mkdir -p Output
	$(Verb)$(JAVAC) -classpath Output -d Output $?
	$(Verb)touch $@

# Compiled bytecode for tests
BYTECODE := $(addsuffix .llvm.bc, $(PREFIXED_JAVA_TESTS))

# Output produced by tests
NATIVE_OUTPUT := $(addsuffix .out-nat, $(PREFIXED_JAVA_TESTS))
JIT_OUTPUT := $(addsuffix .out-jit, $(PREFIXED_JAVA_TESTS))

# Diffs of output produced by native and llvm-java runs
DIFFS := $(addsuffix .diff, $(PREFIXED_JAVA_TESTS))

# Keep the output and diffs
.PRECIOUS: %.out-nat %.out-jit %.diff

# rule to run a .class file with the jvm
%.out-nat: %.class
	-$(Verb)LD_LIBRARY_PATH=$(LibDir) $(JAVA) -cp Output $(notdir $*) \
		> $*.out-nat 2>&1

# rule to run a .class file with the llvm jit
%.out-jit: %.llvm.bc
	-$(Verb)$(LLI) $< > $*.out-jit 2>&1

# rule to diff test output
%.diff: %.out-nat %.out-jit
	$(Verb)diff $*.out-nat $*.out-jit > $@ \
	&& echo "PASS: $(notdir $*)" \
	|| echo "FAIL: $(notdir $*)"

all-local:: $(DIFFS)

endif
