##==-- test/Makefile.test - Common make rules Java tests -*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

include $(LEVEL)/Makefile.common

.PHONY: clean

clean::
	$(Verb)$(RM) -f a.out core
	$(Verb)$(RM) -rf Output/

# we don't want these files to be deleted by make, even if they are
# intermediate results
.PRECIOUS: Output/.dir %.linked.bc %.raw.bc %.ll %.llvm.bc

# -simplifycfg -mem2reg -instcombine 

# rule to link bytecode with runtime
%.llvm %.llvm.bc: %.linked.bc $(LibDir)/libjrt.bca $(EXTRA_OBJS) $(LOPT)
	$(Echo) Linking $< with the Java runtime
	$(Verb)$(GCCLD) -disable-opt -o=$*.llvm $< -L $(LibDir) $(EXTRA_OBJS)

# rule to make assembly from bytecode
%.dis-ll: %.bc
	$(Echo) Disassembling $<
	$(Verb)$(LDIS) -f -o=$@ $<

# rule to compile java sources
ifdef JAVA_TESTS
Output/.compile-java: $(addsuffix .java,$(JAVA_TESTS))
	$(Echo) Compiling $?
	$(Verb)mkdir -p Output
	$(Verb)$(JAVAC) -d Output $?
	$(Verb)touch $@

all:: Output/.compile-java
endif

PREFIXED_JAVA_TESTS := $(addprefix Output/, $(JAVA_TESTS))

# Compiled bytecode for tests
BYTECODE := $(addsuffix .llvm.bc, $(PREFIXED_JAVA_TESTS))

# Output produced by tests
NATIVE_OUTPUT := $(addsuffix .out-nat, $(PREFIXED_JAVA_TESTS))
JIT_OUTPUT := $(addsuffix .out-jit, $(PREFIXED_JAVA_TESTS))

# Diffs of output produced by native and llvm-java runs
DIFFS := $(addsuffix .diff, $(PREFIXED_JAVA_TESTS))

# Keep the output and diffs
.PRECIOUS: %.out-nat %.out-jit %.diff

all:: $(BYTECODE)
all:: $(DIFFS)

# rule to run a .class file with the jvm
%.out-nat: %.class
	$(Echo) Running $(notdir $*) with the host JVM
	-$(Verb)LD_LIBRARY_PATH=$(LibDir) $(JAVA) -cp Output $(notdir $*) > $*.out-nat || rm -f $*.out-nat

# rule to run a .class file with the llvm jit
%.out-jit: %.llvm.bc
	$(Echo) Running $(notdir $*) with the llvm JIT
	-$(Verb)$(LLI) $< > $*.out-jit

# rule to diff test output
%.diff: %.out-nat %.out-jit
	$(Verb)diff $*.out-nat $*.out-jit > $@ || echo "FAIL: $(notdir $*)"
