##==-- test/Makefile.test - Common make rules Java tests -*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

include $(LEVEL)/Makefile.common

.PHONY: clean

clean::
	$(RM) -f a.out core *.class .class-stamp
	$(RM) -rf Output/

# we don't want these files to be deleted by make, even if they are
# intermediate results
.PRECIOUS: Output/.dir %.bc %.ll %.llvm.bc %.llvm %.class

#rule to link in runtime to raw bytecode
%.linked.bc: %.raw.bc $(LEVEL)/runtime/runtime.bc
	$(LLVMTOOLCURRENT)/llvm-link$(EXEEXT) $^ -o $@

# rule to make assembly from bytecode
%.dis-ll: %.bc
	$(LDIS) < $< > $@

# rule to compile java source
%.class: %.java
	$(JAVAC) $<
