##===- ./Makefile ------------------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL := .

DIRS := lib tools runtime
EXTRA_DIST := Makefile.test

include $(LEVEL)/Makefile.common
