##==-- Makefile.rules - Common make rules for Java -------*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

CLASS2LLVM := $(PROJTOOLCURRENT)/class2llvm$(EXEEXT)

# rule to make assembly from bytecode
%.dis-ll: %.bc
	$(LDIS) < $< > $@

# rule to make bytecode from assembly
%.bc: %.ll
	$(LAS) < $< > $@
