##==-- Makefile.rules - Common make rules for Java -------*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LDIS := $(LLVMToolDir)/llvm-dis$(EXEEXT)
LLI := $(LLVMToolDir)/lli$(EXEEXT)
LLINK := $(LLVMToolDir)/llvm-link$(EXEEXT)
LOPT := $(LLVMToolDir)/opt$(EXEEXT)

CLASS2LLVM := $(ToolDir)/class2llvm$(EXEEXT)
CLASSDUMP  := $(ToolDir)/classdump$(EXEEXT)

# rule to make bytecode from assembly
%.bc: %.ll
	$(Echo) Assembling $< to bytecode
	$(Verb)$(LLVMAS) < $< > $@ || rm -f $@
