##===- hlvm/Reader/Makefile --------------------------------*- Makefile -*-===##
#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=XML Yaml

include $(LEVEL)/Makefile.hlvm
