##===- sample/tools/sample/Makefile ------------------------*- Makefile -*-===##

# Indicate where we are relative to the top of the source tree.
LEVEL   := ../..

# Give the name of the tool.
TOOLNAME := Sample

# List libraries that we'll need
# We use LIBS because sample is a dynamic library.
USEDLIBS := sample.a

# The goal for this directory is to link a tool.
GOAL     := tool

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.config
