##==-- runtime/Makefile -----------------------------  -*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL := ..
# FIXME: This needs to be handled by the configure script or alternatively
# import jni.h in the java-fe.
CPPFLAGS+=-I$(HOME)/projects/college/classpath-0.12/include
BYTECODE_LIBRARY=1
LIBRARYNAME=jrt

include $(LEVEL)/Makefile.common
