##==-- runtime/Makefile -----------------------------  -*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL := ..

CPPFLAGS+=-I$(PROJ_SRC_ROOT)/include/llvm/Java
BYTECODE_LIBRARY=1
LIBRARYNAME=jrt

include $(LEVEL)/Makefile.common
