##==-- runtime/Makefile -----------------------------  -*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL := ..

include $(LEVEL)/Makefile.common

all:: runtime.bc

clean::
	rm -f *.bc

