#!/bin/bash

set -e                     # Terminate script at the first line that fails.
set -o pipefail            # Return the first non-zero pipe command error.
set -x                     # Print commands as they are executed

# The fist 2 parameters are consumed by this script and they are:
BUILD_SCRIPT=$1            # Build script name to launch
shift
BUILD_DIR=$1               # Path to the build root directory.
shift
# The rest of the parameters will pass through.

# The build script expects to be run from the build root directory.
cd $BUILD_DIR

# Launch the build script with all the remaining parameters
$BUILD_SCRIPT $@
