##===- test/Regression/ClassFile/Makefile ------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL := ../../..

JAVAFILES := $(wildcard *.java)

include $(LEVEL)/test/Makefile.test
