#!/bin/sh -x
# make a MacOS bundle llvm-tv.app used to encapsulate llvm-tv
# brg Tue Apr 27 15:10:22 CDT 2004
#
APP="$1"
WX="$2"
BINARY="$3"
mkdir ${APP}.app
CONTENTS=${APP}.app/Contents
mkdir $CONTENTS
mkdir ${CONTENTS}/MacOS
mkdir ${CONTENTS}/Resources
# don't know what we need this for...
#/Developer/Tools/Rez -t APPL Carbon.r $WX/lib/libwx_macd-2.4.0.r -o $APP
cp $BINARY ${CONTENTS}/MacOS/${APP}
sed -e "s/IDENTIFIER/llvm-tv/" \
    -e "s/EXECUTABLE/$APP/" \
    -e "s/VERSION/1.0/" $WX/src/mac/Info.plist.in > ${CONTENTS}/Info.plist
echo -n "APPL????" > ${CONTENTS}/PkgInfo
cp $WX/lib/libwx_macd-2.4.0.rsrc ${CONTENTS}/Resources/${APP}.rsrc
cp $WX/src/mac/wxmac.icns ${CONTENTS}/Resources/wxmac.icns
exit 0
