LEVEL = ../..
TOOLNAME = llvm-tv
USEDLIBS =
CPPFLAGS = $(shell $(LEVEL)/lib/wxwindows/wx-config --cflags)
TOOLLINKOPTSB = $(shell $(LEVEL)/lib/wxwindows/wx-config --libs)

include $(LEVEL)/Makefile.common
