##===- sample/lib/Makefile ---------------------------------*- Makefile -*-===##

# Relative path to the top of the source tree.
LEVEL := ..

# Goal of this directory is just descend to the DIRS
GOAL := common

# List all of the subdirectories that we will compile.
DIRS := sample

# Get all the rules to build things.
include $(LEVEL)/Makefile.config
