#===- tools/class2llvm/Makefile ----------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL := ../..

TOOLNAME := class2llvm

USEDLIBS := classfile compiler
LLVMLIBS := support vmcore bcwriter

include $(LEVEL)/Makefile.common
