#===- tools/class2llvm/Makefile ----------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL := ../..

TOOLNAME := class2llvm

USEDLIBS := LLVMJavaCompiler.a LLVMJavaClassfile.a
LLVMLIBS := LLVMBCWriter LLVMCore LLVMSupport.a LLVMbzip2 LLVMSystem.a

include $(LEVEL)/Makefile.common
