##==-- test/Programs/SingleSource/Makefile.singlesrc -----*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

# rule to build raw bytecode from a classfile
%.linked.bc: %.class $(CLASS2LLVM)
	$(Echo) Compiling $< to bytecode
	-$(Verb)$(CLASS2LLVM) \
	  -cp $(CLASSPATH_JAVA_LIBRARY_PATH):$(CLASSPATH):Output \
	  $(subst /,.,$(*F)) -o=$@

include $(LEVEL)/test/Makefile.test
