##==-- test/Programs/SingleSource/Makefile.singlesrc -----*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

# rule to build raw bytecode from a classfile
%.raw.bc: %.class $(CLASS2LLVM)
	@$(ECHO) Compiling $<
	$(CLASS2LLVM) -cp $(CLASSPATH):Output $(subst /,.,$(*F)) | $(LOPT) -mem2reg > $@

include $(LEVEL)/test/Makefile.test
