##==-- test/Programs/SingleSource/Makefile.singlesrc -----*- makefile -*--====##
#
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

# rule to build raw bytecode from a classfile
%.raw.bc: %.class $(CLASS2LLVM)
	$(Echo) Compiling $< to bytecode
	$(Verb)$(CLASS2LLVM) -cp $(CLASSPATH):Output $(subst /,.,$(*F)) -o=$@

# OPT_PASSES := -simplifycfg -mem2reg -globalopt -globaldce \
#               -ipconstprop -deadargelim -instcombine -simplifycfg \
#               -inline -argpromotion -raise -tailduplicate -simplifycfg \
#               -scalarrepl -instcombine -tailcallelim -simplifycfg \
#               -licm -instcombine -indvars -loop-unroll -instcombine \
#               -load-vn -gcse -sccp -instcombine -dse -adce -simplifycfg \
#               -deadtypeelim -constmerge

OPT_PASSES := -simplifycfg -mem2reg -globalopt -globaldce \
              -ipconstprop -deadargelim -instcombine -simplifycfg \
              -inline -argpromotion -raise -tailduplicate -simplifycfg \
              -gcse -sccp -adce -simplifycfg \
              -deadtypeelim -constmerge

# optimize raw bytecode
%.linked.bc: %.raw.bc $(LOPT)
	$(Echo) Optimizing $<
	$(Verb)$(LOPT) $(OPT_PASSES) -f -o=$@ $<

include $(LEVEL)/test/Makefile.test
