#===-- Build Script For HLVM ----------------------------------*- Python -*-===#
#
#                      High Level Virtual Machine (HLVM)
#
# This file was developed by Reid Spencer and is distributed under the
# University of Illinois Open Source License. See LICENSE.TXT for details.
# 
#===------------------------------------------------------------------------===#
from build import hlvm
env = hlvm.GetBuildEnvironment(COMMAND_LINE_TARGETS,ARGUMENTS)
Export('env')
hlvm.Dirs(env,['hlvm','tools','docs','test'])
