# HLVM scons Software Construction Specification
# 

# Set up scons
from os import path
from scons import main
env = main.GetBuildEnvironment(COMMAND_LINE_TARGETS,ARGUMENTS)
Export('env')

SConscript(path.join(env['BuildDir'],'hlvm','SConscript'))
SConscript(path.join(env['BuildDir'],'tools','SConscript'))
