=pod

=head1 NAME

hlvm - HLVM Virtual Machine

=head1 SYNOPSIS

B<hlvm> [I<options>] I<program> I<program-options>

=head1 DESCRIPTION

B<hlvm> is the virtual machine tool for the High Level Virtual Machine. The
I<program> parameter specifies the name of the program to run. The
I<program-options> provide options to that program, not the B<hlvm> runtime. The
I<options> control various aspects of how the program is run. These options are
described below.

=head1 OPTIONS

=over

=item B<--help> or B<-h>

Show the usage help for this tool.

=item B<--version> or B<-v>

Show the version number of this tool.

=back

=head1 EXIT STATUS

The B<hlvm> tool will return the exit code of the program that it runs. If a
hard runtime error occurs, it will return the error number corresponding to that
error (see hlvm/Runtime/Errors.h). 

=head1 AUTHORS

Written by Reid Spencer (L<http://hlvm.org>).

=cut
