##===- tools/hlvm-xml2xml/Makefile -------------------------*- Makefile -*-===##

LEVEL = ../..
TOOLNAME = hlvm-xml2xml
USEDLIBS = HLVMXMLWriter.a HLVMXMLReader.a HLVMAST.a
LLVMLIBS = LLVMSupport.a LLVMSystem.a

include $(LEVEL)/Makefile.hlvm

