from scons import main
Import('env')
env.Program('hlvm-xml2xml', main.GetAllCXXFiles(env),
 LIBS=[
   'HLVMXMLReader',
   'HLVMXMLWriter',
   'HLVMAST',
   'HLVMBase',
   'xml2',
   'LLVMSupport',
   'LLVMSystem',
   'apr-1',
   'stdc++'
  ]
)
